# Generated by Django 4.2.2 on 2024-06-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=200)),
                ('Bussiness', models.CharField(max_length=200)),
                ('Service', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
    ]
