# Generated by Django 4.2.2 on 2024-06-21 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_rename_bussiness_contact_bussiness_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='bussiness',
            new_name='business',
        ),
    ]
